---
- name: Install Essential Tools on Fedora 41 KDE
  hosts: localhost
  become: yes

  tasks:
#    - name: Add Microsoft VS Code repository
#      command: >
#        rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
#        sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
#      args:
#        warn: false
#      changed_when: true

    - name: Install essential tools
      dnf:
        name:
          - neovim           # Vim-based text editor
          - git              # Version control system
          - tmux             # Terminal multiplexer
          - btop             # Modern system monitoring tool
          - ripgrep          # Fast grep alternative
          - fzf              # Fuzzy finder
          - gimp             # GNU Image Manipulation Program
          - fastfetch        # System information tool
          - vlc              # Multimedia player
          - ffmpeg           # Multimedia framework
          - audacity         # Audio editing tool
          - obs-studio       # Video recording and streaming
          - kdenlive         # Video editing software
          - dolphin          # KDE file manager
          - rtorrent         # Command-line BitTorrent client
          - steam            # Gaming platform
          - libreoffice      # Office suite
        state: present
        update_cache: yes

    - name: Add fastfetch command to ~/.bashrc
      lineinfile:
        path: ~/.bashrc
        line: "fastfetch"
        create: yes

    - name: Set vi as default editor in ~/.bashrc
      lineinfile:
        path: ~/.bashrc
        line: "export EDITOR=vi"
        create: yes

    - name: Clean up DNF metadata
      command: dnf clean all
      changed_when: false

